name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://www.ruby-lang.org/en/downloads/branches/
        ruby-version:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: gem build
      - run: gem install --verbose ruzzy-*.gem
        env:
          RUZZY_DEBUG: "1"
          MAKE: "make --environment-overrides V=1"
          CC: "clang"
          CXX: "clang++"
          LDSHARED: "clang -shared"
          LDSHAREDXX: "clang++ -shared"
