name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://apt.llvm.org/bookworm/dists/
        llvm-version:
          # TODO: add 14 to ensure support for Ubuntu 22.04. LLVM doesn't build
          # 14 for Bookworm, so we could switch to Bullseye, or use some other
          # means of testing against LLVM 14. We've manually confirmed 14 works,
          # but having automated tests would ensure compatibility as development
          # continues. Tracking upstream request here:
          # https://github.com/opencollab/llvm-jenkins.debian.net/issues/27
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
          - "21"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image (LLVM ${{ matrix.llvm-version }})
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: ruzzy
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            LLVM_VERSION=${{ matrix.llvm-version }}
      - name: Run tests
        run: |
          docker run \
            --env LD_PRELOAD=$(docker run --entrypoint ruby ruzzy -e 'require "ruzzy"; print Ruzzy::ASAN_PATH') \
            --entrypoint rake \
            ruzzy test

  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - ruby-version: "4.0"
            llvm-version: "21"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install Homebrew LLVM
        run: |
          brew install llvm@${{ matrix.llvm-version }}
          echo "/opt/homebrew/opt/llvm@${{ matrix.llvm-version }}/bin" >> "$GITHUB_PATH"
      - run: gem build
      - run: gem install --verbose --development ruzzy-*.gem
        env:
          RUZZY_DEBUG: "1"
          MAKE: "make --environment-overrides V=1"
          CC: clang
          CXX: clang++
          LDSHARED: clang -dynamic -bundle -undefined dynamic_lookup
          LDSHAREDXX: clang++ -dynamic -bundle -undefined dynamic_lookup
      - name: Run tests
        run: |
          DYLD_INSERT_LIBRARIES=$(arch -arm64 ruby -e 'require "ruzzy"; print Ruzzy::ASAN_PATH') \
            arch -arm64 rake test
